services:
  web:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: true
      - path: .env.production.local
        required: true
    volumes:
      - ./logs:/logs
  postgres:
    image: postgres:17-alpine
    env_file:
      - path: .env
        required: true
      - path: .env.production.local
        required: true
    volumes:
      - postgres:/var/lib/postgresql/data
